/**
 * Extracurricular options for searchable multi-select.
 */

export const EXTRACURRICULAR_OPTIONS: string[] = [
  "Robotics Team",
  "Debate Team",
  "Student Government",
  "Coding Club",
  "Math Club",
  "Science Olympiad",
  "Volunteer Tutoring",
  "Research Internship",
  "Hackathons",
  "Startup Club",
  "Model UN",
  "Varsity Sports",
  "JV Sports",
  "School Newspaper",
  "Music Ensemble",
  "Band",
  "Orchestra",
  "Choir",
  "Theater",
  "Drama Club",
  "Community Service",
  "Key Club",
  "National Honor Society",
  "Environmental Club",
  "Girls Who Code",
  "Black Student Union",
  "Latinx Student Association",
  "Asian Student Association",
  "LGBTQ+ Alliance",
  "Yearbook",
  "Photography Club",
  "Art Club",
  "Chess Club",
  "Quiz Bowl",
  "Mock Trial",
  "Youth Advisory Board",
  "Internship",
  "Part-time Job",
  "Church/Youth Group",
  "Scouts",
  "Dance Team",
  "Cheerleading",
];
