/**
 * Interest options for searchable multi-select.
 */

export const INTEREST_OPTIONS: string[] = [
  "Machine Learning",
  "Robotics",
  "Startups",
  "Mathematics",
  "Climate Tech",
  "Medicine",
  "Debate",
  "Writing",
  "Creative Writing",
  "Art",
  "Community Service",
  "Open Source",
  "Hackathons",
  "Research",
  "Leadership",
  "Product Design",
  "Game Development",
  "Cybersecurity",
  "Data Analytics",
  "Environmental Advocacy",
  "Music",
  "Theater",
  "Sports",
  "Photography",
  "Philosophy",
  "Economics",
  "Politics",
  "Law",
  "Teaching",
  "Journalism",
  "Social Impact",
  "Space & Aerospace",
  "Neuroscience",
  "Genetics",
  "Finance",
  "Architecture",
];
