/**
 * Intended major options for searchable multi-select.
 */

export const MAJOR_OPTIONS: string[] = [
  "Computer Science",
  "Artificial Intelligence",
  "Data Science",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Biomedical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Aerospace Engineering",
  "Mathematics",
  "Applied Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Neuroscience",
  "Economics",
  "Business",
  "Finance",
  "Accounting",
  "Marketing",
  "Political Science",
  "International Relations",
  "Psychology",
  "Sociology",
  "Design",
  "Graphic Design",
  "Architecture",
  "Urban Planning",
  "English",
  "History",
  "Philosophy",
  "Communications",
  "Film & Media",
  "Education",
  "Nursing",
  "Pre-Medicine",
  "Pre-Law",
  "Environmental Science",
  "Public Policy",
];
